### ISSUE TITLE
Allow showing finish-args if specified

### ISSUE THREAD

**Issue by ryonakano** [dar5hak/flatpak-modules#5]
Some modules requires special `finish-args` being set and won't work properly without them, so it would be helpful if we could also show these info if specified in the json file.

For example, `gst-libav` requires setting `GST_PLUGIN_PATH_1_0` environment path so that the app can detect the compiled module:

```yaml
finish-args:
  - '--socket=pulseaudio'
  - '--env=GST_PLUGIN_PATH_1_0=/app/lib/gstreamer-1.0' # this is necessary
modules:
  - name: gst-libav
    buildsystem: meson
    sources:
      - type: archive
        url: https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.18.5.tar.xz
        sha256: 822e008a910e9dd13aedbdd8dc63fedef4040c0ee2e927bab3112e9de693a548
```

The current design of `public/modules.json` is just allowing to specify the section under `modules` and not allowing to specify `finish-args` which is the same hierarchy with `modules` section.
